# -*- coding: utf-8 -*-
"""day09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16AtPxsWhG0USeHf91Crvms3DWewKcfJb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler  , LabelEncoder
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split , cross_val_score , GridSearchCV
from catboost  import CatBoostClassifier

data = pd.read_csv('data.csv')

data.head()

X = data.drop(columns=['Date' , 'City' , 'Type'])
Y = data['Type']

y_le = LabelEncoder()
Y = y_le.fit_transform(Y)



X_train , X_test , y_train , y_test = train_test_split(X , Y , test_size=0.3 , random_state=42)

X.describe()

model = CatBoostClassifier(
    silent=True,
    random_seed=42
)

param_grid = {
    'iterations': [ 500 ],
    'learning_rate': [0.01, 0.1],
    'depth': [4, 6, 8 ],

}

grid = GridSearchCV(estimator=model, param_grid=param_grid,
                    scoring='accuracy', cv=3, n_jobs=-1, verbose=1)

grid.fit(X_train, y_train)


print("Best Parameters:")
print(grid.best_params_)

print("Best Score:")
print(grid.best_score_)

best_param = grid.best_params_

cbg = CatBoostClassifier(**best_param)

cbg.fit(X_train , y_train)

y_pred = cbg.predict(X_test)

print(r2_score(y_test , y_pred))

